// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type elmerBpfExecEvent struct {
	_        structs.HostLayout
	Kind     uint32
	Tgid     uint32
	Pid      uint32
	Uid      uint32
	Gid      uint32
	Comm     [16]int8
	Filename [128]int8
	ArgvLen  uint32
	Argv     [512]int8
}

type elmerBpfSockEvent struct {
	_      structs.HostLayout
	Kind   uint32
	Tgid   uint32
	Uid    uint32
	Family uint16
	Port   uint16
	Addr   [16]uint8
	Comm   [16]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	elmerBpfMapEvents         = "events"
	elmerBpfMapTypeAnchorExec = "type_anchor_exec"
	elmerBpfMapTypeAnchorSock = "type_anchor_sock"
	elmerBpfProgTraceBind     = "trace_bind"
	elmerBpfProgTraceConnect  = "trace_connect"
	elmerBpfProgTraceExecve   = "trace_execve"
	elmerBpfProgTraceExecveat = "trace_execveat"
)

// loadElmerBpf returns the embedded CollectionSpec for elmerBpf.
func loadElmerBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ElmerBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load elmerBpf: %w", err)
	}

	return spec, err
}

// loadElmerBpfObjects loads elmerBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*elmerBpfObjects
//	*elmerBpfPrograms
//	*elmerBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadElmerBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadElmerBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// elmerBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type elmerBpfSpecs struct {
	elmerBpfProgramSpecs
	elmerBpfMapSpecs
	elmerBpfVariableSpecs
}

// elmerBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type elmerBpfProgramSpecs struct {
	TraceBind     *ebpf.ProgramSpec `ebpf:"trace_bind"`
	TraceConnect  *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceExecve   *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveat *ebpf.ProgramSpec `ebpf:"trace_execveat"`
}

// elmerBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type elmerBpfMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	TypeAnchorExec *ebpf.MapSpec `ebpf:"type_anchor_exec"`
	TypeAnchorSock *ebpf.MapSpec `ebpf:"type_anchor_sock"`
}

// elmerBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type elmerBpfVariableSpecs struct {
}

// elmerBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadElmerBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type elmerBpfObjects struct {
	elmerBpfPrograms
	elmerBpfMaps
	elmerBpfVariables
}

func (o *elmerBpfObjects) Close() error {
	return _ElmerBpfClose(
		&o.elmerBpfPrograms,
		&o.elmerBpfMaps,
	)
}

// elmerBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadElmerBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type elmerBpfMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	TypeAnchorExec *ebpf.Map `ebpf:"type_anchor_exec"`
	TypeAnchorSock *ebpf.Map `ebpf:"type_anchor_sock"`
}

func (m *elmerBpfMaps) Close() error {
	return _ElmerBpfClose(
		m.Events,
		m.TypeAnchorExec,
		m.TypeAnchorSock,
	)
}

// elmerBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadElmerBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type elmerBpfVariables struct {
}

// elmerBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadElmerBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type elmerBpfPrograms struct {
	TraceBind     *ebpf.Program `ebpf:"trace_bind"`
	TraceConnect  *ebpf.Program `ebpf:"trace_connect"`
	TraceExecve   *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveat *ebpf.Program `ebpf:"trace_execveat"`
}

func (p *elmerBpfPrograms) Close() error {
	return _ElmerBpfClose(
		p.TraceBind,
		p.TraceConnect,
		p.TraceExecve,
		p.TraceExecveat,
	)
}

func _ElmerBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed elmerbpf_bpfeb.o
var _ElmerBpfBytes []byte
