package detect

import "elmer/internal/events"

// builtinRules is the shipped detection set. Severity here only escalates;
// monitors set baseline severities and the engine raises, never lowers.
var builtinRules = []ruleDef{
	// ---- Reverse shells -------------------------------------------------
	{ID: "rshell-devtcp", Title: "Reverse shell (bash /dev/tcp)", Technique: "T1059.004",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)(bash|sh|zsh|dash|ksh)[^\n]{0,60}-i[^\n]{0,60}(/dev/(tcp|udp)/|>&\s*/dev/(tcp|udp))`},
	{ID: "rshell-netcat", Title: "Reverse shell (netcat -e)", Technique: "T1059.004",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\bnc(at)?\b[^\n|]{0,80}\s-e\s+`},
	{ID: "rshell-socat", Title: "Reverse shell / relay (socat)", Technique: "T1059.004",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\bsocat\b[^\n]{0,120}(exec:|SYSTEM:|TCP:.*fork)`},
	{ID: "rshell-python", Title: "Reverse shell (python)", Technique: "T1059.006",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\bpython[23]?\b[^\n]{0,200}(pty\.spawn|socket\.socket|subprocess\.call\(\s*\[?\s*['"]/bin/(ba)?sh)`},
	{ID: "rshell-perl", Title: "Reverse shell (perl)", Technique: "T1059.006",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\bperl\b[^\n]{0,40}\s-e[^\n]{0,200}(IO::Socket|socket\(|exec\s*\(|/bin/(ba)?sh)`},
	{ID: "rshell-ruby", Title: "Reverse shell (ruby)", Technique: "T1059.006",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\bruby\b[^\n]{0,60}(-rsocket|-e[^\n]{0,200}(TCPSocket|fsockopen))`},
	{ID: "rshell-php", Title: "Reverse shell (php)", Technique: "T1059.008",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\bphp\b[^\n]{0,30}\s-r[^\n]{0,200}(fsockopen|socket_create|exec\s*\(\s*['"]/bin/(ba)?sh)`},
	{ID: "rshell-mkfifo", Title: "FIFO reverse shell", Technique: "T1059.004",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)mkfifo[^\n|]{0,100}(|\||;)[^\n]{0,100}(/bin/(ba)?sh|sh\s+-i)`},
	{ID: "ps-enc", Title: "Encoded PowerShell command", Technique: "T1027",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)powershell(.exe)?[^\n]{0,120}-e(nc(odedcommand)?)?\s+[A-Za-z0-9+/=]{20,}`},
	{ID: "download-exec", Title: "Downloaded script piped to shell", Technique: "T1059.004",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)(curl|wget)[^\n|]{0,200}\|\s*(sudo\s+)?(ba|z|da|k)?sh\b`},
	{ID: "download-shm", Title: "Download into /dev/shm", Technique: "T1105",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)(curl|wget)[^\n]{0,150}(-o\s+|--output[-a-z]*\s+)?/dev/shm/`},

	// ---- Tunnels ---------------------------------------------------------
	{ID: "tunnel-chisel", Title: "Chisel tunnel tool", Technique: "T1090",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)(^|[\\/])chisel(\.exe)?(\s|$)`},
	{ID: "tunnel-frp", Title: "FRP tunnel tool", Technique: "T1090",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)(^|[\\/])frp[cs](\s|$)`},
	{ID: "tunnel-ngrok", Title: "ngrok tunnel", Technique: "T1090",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)(^|[\\/])ngrok(\s|$)`},
	{ID: "tunnel-socat-listen", Title: "socat listener/relay", Technique: "T1090",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\bsocat\b[^\n]{0,120}TCP-LISTEN`},
	{ID: "tunnel-ssh-forward", Title: "SSH port forward / SOCKS proxy", Technique: "T1572",
		Target: TargetProcess, Severity: events.Medium,
		Pattern: `(?i)\bssh\b[^\n]{0,80}\s-\w*[DLR]\b`},
	{ID: "tunnel-dns", Title: "DNS tunneling tool", Technique: "T1071.004",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)(^|[\\/])(iodine|dnscat2?)(\s|$)`},

	// ---- Credential access ----------------------------------------------
	{ID: "cred-mimikatz", Title: "Mimikatz", Technique: "T1003.001",
		Target: TargetAny, Severity: events.Critical,
		Pattern: `(?i)mimikatz`},
	{ID: "cred-shadow-read", Title: "/etc/shadow accessed", Technique: "T1003.008",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\b(cat|cp|mv|chmod|chown|less|more|head|tail|vim|vi|nano|base64|xxd|strings|grep|awk|python[23]?)\b[^\n]{0,80}/etc/shadow`},
	{ID: "cred-lsass", Title: "LSASS memory dump", Technique: "T1003.001",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)(procdump[^\n]{0,80}-ma[^\n]{0,80}lsass|(comsvcs|dbg\.core)\.dll[^\n]{0,80}(MiniDump|24)|rundll32[^\n]{0,120}comsvcs\.dll,\s*MiniDump)`},
	{ID: "cred-regsave", Title: "SAM/SYSTEM registry hive dump", Technique: "T1003.002",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\breg\b[^\n]{0,60}\bsave\b[^\n]{0,80}(HKLM|hklm)[^\n]{0,40}(sam|system|security)`},
	{ID: "cred-vssadmin", Title: "Shadow copy deletion", Technique: "T1490",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\bvssadmin\b[^\n]{0,60}delete\s+shadows`},
	{ID: "cred-ntds", Title: "NTDS/secrets dump", Technique: "T1003.003",
		Target: TargetAny, Severity: events.Critical,
		Pattern: `(?i)(ntdsutil|secretsdump|hashdump)\b`},
	{ID: "cred-hashcat", Title: "Credential cracking", Technique: "T1110",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)(^|[\\/])(hashcat|john|hydra|medusa)(\s|$)`},

	// ---- LOLBins / living off the land ----------------------------------
	{ID: "lol-certutil", Title: "certutil download", Technique: "T1105",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\bcertutil\b[^\n]{0,120}(-urlcache|-verifyctl)\s`},
	{ID: "lol-bitsadmin", Title: "bitsadmin transfer", Technique: "T1105",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\bbitsadmin\b[^\n]{0,120}/(transfer|create)`},
	{ID: "lol-mshta", Title: "mshta remote/script execution", Technique: "T1218.005",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\bmshta\b[^\n]{0,160}(https?://|javascript:|vbscript:)`},
	{ID: "lol-rundll32", Title: "rundll32 script/remote execution", Technique: "T1218.011",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\brundll32\b[^\n]{0,160}(javascript:|https?://)`},
	{ID: "lol-regsvr32", Title: "regsvr32 scriptlet execution", Technique: "T1218.010",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\bregsvr32\b[^\n]{0,120}/i:https?://`},
	{ID: "lol-msbuild", Title: "msbuild remote/project build", Technique: "T1127.001",
		Target: TargetProcess, Severity: events.Medium,
		Pattern: `(?i)\bmsbuild\b[^\n]{0,120}(https?://|\\AppData\\|/tmp/)`},

	// ---- Persistence actions --------------------------------------------
	{ID: "persist-useradd", Title: "User account created", Technique: "T1136.001",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)(^|[\\/])(useradd|adduser)(\s|$)`},
	{ID: "persist-usermod", Title: "Account modified (usermod)", Technique: "T1136",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\busermod\b[^\n]{0,120}(-u|-g|-G|-a|-s|root|wheel|sudo|0)`},
	{ID: "persist-netuser", Title: "Windows user account created", Technique: "T1136.001",
		Target: TargetProcess, Severity: events.Critical,
		Pattern: `(?i)\bnet\s+(user|localgroup)[^\n]{0,120}/add\b`},
	{ID: "persist-schtasks", Title: "Scheduled task created", Technique: "T1053.005",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)(^|[\\/])schtasks(\.exe)?[^\n]{0,160}/create\b`},
	{ID: "persist-crontab", Title: "crontab modified", Technique: "T1053.003",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\bcrontab\b[^\n]{0,80}(-e|--edit|-r|--remove|-l\s*>|/tmp/)`},
	{ID: "persist-chmod-suid", Title: "SUID/SGID bit set via chmod", Technique: "T1548.001",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\bchmod\b\s+(-[a-zA-Z]+\s+)*[0-7]{0,2}[2-7][0-7]{3}\b|\bchmod\b[^\n]{0,80}\+[ug]*s\b`},
	{ID: "persist-setcap", Title: "Dangerous capability granted (setcap)", Technique: "T1548",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)\bsetcap\b[^\n]{0,120}(cap_setuid|cap_net_admin|cap_sys_ptrace|cap_dac_override)`},
	{ID: "persist-at-job", Title: "at job scheduled", Technique: "T1053.002",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)(^|[\\/])at(\.exe)?\s+-[fm]\s|(^|[\\/])atq(\s|$)`},

	// ---- Anti-forensics --------------------------------------------------
	{ID: "antiforensics-history", Title: "Shell history cleared", Technique: "T1070.003",
		Target: TargetProcess, Severity: events.Medium,
		Pattern: `(?i)(history\s+-c\b|unset\s+HISTFILE|export\s+HISTFILE=/dev/null)`},
	{ID: "antiforensics-shred", Title: "Log/file destruction", Technique: "T1070",
		Target: TargetProcess, Severity: events.High,
		Pattern: `(?i)(\brm\b[^\n]{0,120}(\.bash_history|/var/log/)|\bshred\b|\bwipe\b|\bchattr\b[^\n]{0,40}[+-]i\b|wevtutil[^\n]{0,80}cl\b)`},

	// ---- Recon from this host -------------------------------------------
	{ID: "recon-nmap", Title: "Network scanner run from this host", Technique: "T1046",
		Target: TargetProcess, Severity: events.Medium,
		Pattern: `(?i)(^|[\\/])(nmap|masscan|zmap|naabu)(\s|$)`},
	{ID: "recon-whoami-priv", Title: "Privilege enumeration", Technique: "T1033",
		Target: TargetProcess, Severity: events.Low,
		Pattern: `(?i)\bwhoami\b\s+/priv|\bid\b\s+(-a|--all)|\bnet\s+(user|group|localgroup)\s+`},
	{ID: "recon-enum", Title: "Host enumeration tool", Technique: "T1082",
		Target: TargetProcess, Severity: events.Medium,
		Pattern: `(?i)(^|[\\/])(winpeas|linpeas|linux-exploit-suggester|seatbelt|lazagne)(\.[a-z0-9]{1,5})?(\s|$)`},

	// ---- Path rules (FIM) -------------------------------------------------
	{ID: "fim-preload", Title: "ld.so.preload persistence", Technique: "T1546.012",
		Target: TargetPath, Severity: events.Critical,
		Pattern: `(?i)(^|/)ld\.so\.preload$`},
	{ID: "fim-ssh", Title: "SSH trust material changed", Technique: "T1098.004",
		Target: TargetPath, Severity: events.Critical,
		Pattern: `(?i)/\.ssh/(authorized_keys|authorized_keys2|id_[dr]sa.*|id_ed25519.*|known_hosts)$`},
	{ID: "fim-auth-db", Title: "Authentication database changed", Technique: "T1136",
		Target: TargetPath, Severity: events.Critical,
		Pattern: `(?i)/(passwd|shadow|group|gshadow|sudoers|sudoers\.d/.+|ssh/sshd_config.*)$`},
	{ID: "fim-persist", Title: "Persistence location changed", Technique: "T1053",
		Target: TargetPath, Severity: events.High,
		Pattern: `(?i)(/cron\.|/crontab|/systemd/system/.+|/rc\.local$|/profile\.d/.+|/\.bashrc$|/\.profile$|/\.bash_logout$|Windows.+(CurrentVersion.+Run|Start Menu.+Startup|Tasks))`},
	{ID: "fim-binaries", Title: "Binary directory changed", Technique: "T1036",
		Target: TargetPath, Severity: events.High,
		Pattern: `(?i)^/(usr/)?(bin|sbin|lib)/|/usr/local/(bin|sbin)/`},

	// ---- Log-line rules (auth) -------------------------------------------
	{ID: "auth-sudo-su", Title: "Privilege escalation via su", Technique: "T1548",
		Category: events.CatAuth, Target: TargetLine, Severity: events.Medium,
		Pattern: `(?i)Successful su for `},
	{ID: "auth-new-group", Title: "Privileged group changed", Technique: "T1484",
		Category: events.CatAuth, Target: TargetLine, Severity: events.High,
		Pattern: `(?i)(useradd|usermod|gpasswd|groupadd)\[\d+\]:.*(new group|add.*to group|add user)`},
}
